pub const NAMES: [&str; 200] = [
    "Sugar",
    "Junior",
    "Rainbow",
    "Maestro",
    "Chico",
    "Angel",
    "Inchworm",
    "Hammer",
    "Lover",
    "Donuts",
    "Dunce",
    "Figgy",
    "Ladybug",
    "Slim",
    "Nerd",
    "Music Man",
    "Mountain",
    "Dracula",
    "Buttercup",
    "Taco",
    "Short Shorts",
    "Bessie",
    "Drake",
    "Ginger",
    "Belle",
    "Beauty",
    "Pickles",
    "Buckeye",
    "Goonie",
    "Butter",
    "Conductor",
    "Cutie Pie",
    "Bumblebee",
    "Double Bubble",
    "Dirty Harry",
    "Silly Gilly",
    "Gumdrop",
    "Sweetums",
    "Luna",
    "Snoopy",
    "Bug",
    "Bridge",
    "Tiny",
    "MomBod",
    "Baby Maker",
    "Rumplestiltskin",
    "Peppa Pig",
    "Dolly",
    "Blondie",
    "Cannoli",
    "Terminator",
    "Janitor",
    "Coke Zero",
    "Goblin",
    "Pig",
    "Dud",
    "Green Giant",
    "Hot Sauce",
    "Friendo",
    "Mustache",
    "Mr. Clean",
    "Tomcat",
    "Baby Carrot",
    "Lil Girl",
    "Monkey",
    "Grumpy",
    "Silly Sally",
    "Mini Mini",
    "Pickle",
    "Bambi",
    "Foxy Lady",
    "Bubblegum",
    "String Bean",
    "Fattykins",
    "Duckling",
    "Harry Potter",
    "Raisin",
    "Pecan",
    "Smirk",
    "Frankfurter",
    "4-Wheel",
    "Loser",
    "Dum Dum",
    "Chain",
    "Chicken Legs",
    "Flyby",
    "Marge",
    "Mouse",
    "Chance",
    "Moose",
    "Munchkin",
    "Bunny",
    "Dearey",
    "Pyscho",
    "Chum",
    "Creedence",
    "Flower",
    "Smudge",
    "Frodo",
    "Chuckles",
    "Headlights",
    "Baby",
    "Doofus",
    "Stud",
    "Dottie",
    "Boo Bear",
    "Snuggles",
    "Mini Me",
    "Senior",
    "Weirdo",
    "Candy",
    "Beanpole",
    "Cotton",
    "Babe",
    "Buddy",
    "Birdy",
    "Muffin",
    "Buster",
    "Filly Fally",
    "Boomhauer",
    "Captain",
    "Knucklebutt",
    "Biscuit",
    "Rabbit",
    "Dinosaur",
    "Cold Brew",
    "Tootsie",
    "Twinkly",
    "Ace",
    "Rosie",
    "Pookie",
    "Apple Jack",
    "Twiggy",
    "Itchy",
    "Bud",
    "Doctor",
    "Squirt",
    "Cowboy",
    "Barbie",
    "Cold Front",
    "Senorita",
    "Dulce",
    "Autumn",
    "Little Bear",
    "Rosebud",
    "Sassy",
    "Elf",
    "Winnie",
    "Superman",
    "Candycane",
    "Chicken Wing",
    "Shrinkwrap",
    "Dino",
    "Focker",
    "Dots",
    "Pixie Stick",
    "Red Velvet",
    "Goose",
    "Manatee",
    "Guy",
    "Fiesta",
    "Chump",
    "Dummy",
    "Mini Skirt",
    "Raindrop",
    "Bubba",
    "Champ",
    "Princess",
    "Brutus",
    "Herp Derp",
    "Cheesestick",
    "Doc",
    "Pinata",
    "Starbuck",
    "Sunny",
    "Buds",
    "Foxy Mama",
    "Fury",
    "Pop Tart",
    "Ghoulie",
    "Con",
    "Fifi",
    "Ducky",
    "Dumbledore",
    "Dot",
    "Cottonball",
    "Halfmast",
    "Ringo",
    "Gummy Pop",
    "Einstein",
    "Chip",
    "C-Dawg",
    "Fatty",
    "Apple",
    "Mimi",
    "Button",
    "Cheese",
    "Bubbles",
    "Baby Boo",
    "Kit-Kat",
];
